// Pair is a type which is generated by cons procedure.
// Pair has two pointers, which are named car and cdr.
//
// List is expressed by linked list of Pair.
// And procedure application has list which consists of Pair
// as its arguments.

package scheme

import (
	"fmt"
	"strings"
)

type Pair struct {
	ObjectBase
	Car         Object
	Cdr         *Pair
	environment *Environment
}

func (p *Pair) Eval() Object {
	return p
}

func (p *Pair) String() string {
	if p.IsEmpty() {
		return "()"
	} else if p.IsList() {
		length := p.ListLength()
		tokens := []string{}
		for i := 0; i < length; i++ {
			tokens = append(tokens, p.ElementAt(i).Eval().String())
		}
		return fmt.Sprintf("(%s)", strings.Join(tokens, " "))
	} else {
		return "Not implemented. (Pair.String())"
	}
}

func (p *Pair) IsPair() bool {
	return true
}

func (p *Pair) IsList() bool {
	pair := p

	for {
		if pair.IsEmpty() {
			return true
		}
		pair = pair.Cdr
	}
	return false
}

func (p *Pair) ElementAt(index int) Object {
	if !p.IsList() {
		panic("ElementAt() was called for not list object")
	} else if index < 0 {
		panic("ElementAt() was called with negative index")
	}

	pair := p
	for {
		if index == 0 {
			return pair.Car
		} else {
			pair = pair.Cdr
			index--
		}
	}
}

func (p *Pair) IsEmpty() bool {
	return p.Car == nil && p.Cdr == nil
}

func (p *Pair) ListLength() int {
	if p.IsEmpty() {
		return 0
	} else {
		return p.Cdr.ListLength() + 1
	}
}
